# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.12.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.12.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/raphael/Documents/CPP/Purple-Rain

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/raphael/Documents/CPP/Purple-Rain

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.12.4/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.12.4/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/raphael/Documents/CPP/Purple-Rain/CMakeFiles /Users/raphael/Documents/CPP/Purple-Rain/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/raphael/Documents/CPP/Purple-Rain/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Purple-Rain

# Build rule for target.
Purple-Rain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Purple-Rain
.PHONY : Purple-Rain

# fast build rule for target.
Purple-Rain/fast:
	$(MAKE) -f CMakeFiles/Purple-Rain.dir/build.make CMakeFiles/Purple-Rain.dir/build
.PHONY : Purple-Rain/fast

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/Purple-Rain.dir/build.make CMakeFiles/Purple-Rain.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/Purple-Rain.dir/build.make CMakeFiles/Purple-Rain.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/Purple-Rain.dir/build.make CMakeFiles/Purple-Rain.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Rain/Canvas.o: src/Rain/Canvas.cpp.o

.PHONY : src/Rain/Canvas.o

# target to build an object file
src/Rain/Canvas.cpp.o:
	$(MAKE) -f CMakeFiles/Purple-Rain.dir/build.make CMakeFiles/Purple-Rain.dir/src/Rain/Canvas.cpp.o
.PHONY : src/Rain/Canvas.cpp.o

src/Rain/Canvas.i: src/Rain/Canvas.cpp.i

.PHONY : src/Rain/Canvas.i

# target to preprocess a source file
src/Rain/Canvas.cpp.i:
	$(MAKE) -f CMakeFiles/Purple-Rain.dir/build.make CMakeFiles/Purple-Rain.dir/src/Rain/Canvas.cpp.i
.PHONY : src/Rain/Canvas.cpp.i

src/Rain/Canvas.s: src/Rain/Canvas.cpp.s

.PHONY : src/Rain/Canvas.s

# target to generate assembly for a file
src/Rain/Canvas.cpp.s:
	$(MAKE) -f CMakeFiles/Purple-Rain.dir/build.make CMakeFiles/Purple-Rain.dir/src/Rain/Canvas.cpp.s
.PHONY : src/Rain/Canvas.cpp.s

src/Rain/Drop.o: src/Rain/Drop.cpp.o

.PHONY : src/Rain/Drop.o

# target to build an object file
src/Rain/Drop.cpp.o:
	$(MAKE) -f CMakeFiles/Purple-Rain.dir/build.make CMakeFiles/Purple-Rain.dir/src/Rain/Drop.cpp.o
.PHONY : src/Rain/Drop.cpp.o

src/Rain/Drop.i: src/Rain/Drop.cpp.i

.PHONY : src/Rain/Drop.i

# target to preprocess a source file
src/Rain/Drop.cpp.i:
	$(MAKE) -f CMakeFiles/Purple-Rain.dir/build.make CMakeFiles/Purple-Rain.dir/src/Rain/Drop.cpp.i
.PHONY : src/Rain/Drop.cpp.i

src/Rain/Drop.s: src/Rain/Drop.cpp.s

.PHONY : src/Rain/Drop.s

# target to generate assembly for a file
src/Rain/Drop.cpp.s:
	$(MAKE) -f CMakeFiles/Purple-Rain.dir/build.make CMakeFiles/Purple-Rain.dir/src/Rain/Drop.cpp.s
.PHONY : src/Rain/Drop.cpp.s

src/Utils.o: src/Utils.cpp.o

.PHONY : src/Utils.o

# target to build an object file
src/Utils.cpp.o:
	$(MAKE) -f CMakeFiles/Purple-Rain.dir/build.make CMakeFiles/Purple-Rain.dir/src/Utils.cpp.o
.PHONY : src/Utils.cpp.o

src/Utils.i: src/Utils.cpp.i

.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) -f CMakeFiles/Purple-Rain.dir/build.make CMakeFiles/Purple-Rain.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s

.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) -f CMakeFiles/Purple-Rain.dir/build.make CMakeFiles/Purple-Rain.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Purple-Rain"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Rain/Canvas.o"
	@echo "... src/Rain/Canvas.i"
	@echo "... src/Rain/Canvas.s"
	@echo "... src/Rain/Drop.o"
	@echo "... src/Rain/Drop.i"
	@echo "... src/Rain/Drop.s"
	@echo "... src/Utils.o"
	@echo "... src/Utils.i"
	@echo "... src/Utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

